### ISSUE TITLE
Problem install container nginx-proxy

### ISSUE THREAD

**Issue by zatuz** [Cloudbox/Cloudbox#266]
problem when installing mediabox
Problem install  container nginx-proxy
```
System: ubuntu server 16.04 minimal
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error starting container d7c44f4c9507e5117e843c5b0558ddfd1d82f652ae7bf6d37dd232ae9a3ae68d: 400 Client Error: Bad Request (\"OCI runtime create failed: container_linux.go:344: starting container process caused \"process_linux.go:424: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/etc/localtime\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/overlay2/ce0b11d99bb4b59effa7bbf0f0f6cbdd8e8a8c7368f6459e8348815e7a26c2dc/merged\\\\\\\" at \\\\\\\"/var/lib/docker/overlay2/ce0b11d99bb4b59effa7bbf0f0f6cbdd8e8a8c7368f6459e8348815e7a26c2dc/merged/usr/share/zoneinfo/UTC\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type\")"}
```

![error cloudbox](https://user-images.githubusercontent.com/39281593/52896266-eb091680-318a-11e9-8128-f537f7ac169e.jpg)

**Comment by desimaniac** [comment]
This error happens when it couldn’t pull the docker image. It’s more than likely a fluke and should fix itself if you retry.

**Comment by desimaniac** [comment]
This should be fixed. 

```
cd ~/cloudbox && git fetch && git reset --hard FETCH_HEAD
```

And rerun the tag.

**Comment by zatuz** [comment]
hello good day Desimaniac

I try how you told me but the message error persist
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error starting container a3a666462e723b6ce2ff2fb9b0443aa9950877b258b4e652eabd757a8b7a1fa6: 400 Client Error: Bad Request (\"OCI runtime create failed: container_linux.go:344: starting container process caused \"process_linux.go:424: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/etc/localtime\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/overlay2/0d8ef44beb73da8de454289bddee17c5b3c74d1c8a45fa388d9b3c8d80f6c574/merged\\\\\\\" at \\\\\\\"/var/lib/docker/overlay2/0d8ef44beb73da8de454289bddee17c5b3c74d1c8a45fa388d9b3c8d80f6c574/merged/usr/share/zoneinfo/UTC\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type\")"}
```
Test provee in
Ubuntu 16.04 min
Ubuntu 18.04 min

Do you know any way to install the versión 1.3.2 to see if it works correctly? 

I worked whit cloudbox before but not with the versión 1.3.3
![error 2](https://user-images.githubusercontent.com/39281593/53498636-4e892300-3a6c-11e9-94a7-8fb38ad2c17b.png)

**Comment by desimaniac** [comment]
`git pull` and try again.

**Comment by pilonull** [comment]
I am also having this issue.. I've reran dependency installer script and pulled the latest changes, trying to run "sudo ansible-playbook cloudbox.yml --tags cloudbox" and am getting exactly what zatuz is getting.

**Comment by desimaniac** [comment]
run

```
sudo ansible-playbook cloudbox.yml --tags -vvv
```

and paste the logs on pastebin/pastee. 

Also 

```
stat /etc/localtime
```

**Comment by pilonull** [comment]
https://pastebin.com/thfkv8Fg

**Comment by desimaniac** [comment]
I made a typo with the ansible command, `system` was supposed to be in there.

**Comment by desimaniac** [comment]
Well i pushed a possible fix, `git pull` and run 

```
sudo ansible-playbook cloudbox.yml --tags system -vvv
```

**Comment by pilonull** [comment]
I got further assistance from discord but this issue is now solved for me.

**Comment by zatuz** [comment]
https://pastebin.com/30N2S3G2

**Comment by desimaniac** [comment]
@zatuz `sudo  apt-get install --reinstall tzdata` and retry install.

**Comment by zatuz** [comment]
Thanks a lot problem solved
